voxpupuli/puppet-syntax

lib/puppet-syntax.rb
spec/puppet-syntax_spec.rb

Previously, config reader methods would return a new array for the default
value of paths, so if a user did:
PuppetSyntax.exclude_paths << "spec/fixtures/**/*.pp"
e.g. in puppetlabs_spec_helper, then the new path would get appended to the
new array and not change the actual configuration.  Now the array is set as
the default first, so in-place modifications of arrays are preserved.
---
The puppetlabs_spec_helper code assumes this works (as it does in puppet-lint and other gems): https://github.com/puppetlabs/puppetlabs_spec_helper/blob/0.8.2/lib/puppetlabs_spec_helper/rake_tasks.rb#L208.  Similarly if you try and append more paths in your own Rakefile, they're silently ignored.

Let Array#<< modify default configuration values

---

lib/puppet-syntax.rb
lib/puppet-syntax/manifests.rb
lib/puppet-syntax/tasks/puppet-syntax.rb
spec/fixtures/test_module/manifests/deprecation_notice.pp
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax_spec.rb

A simple change so that deprecation notices are printed, but don't cause test failures. A possible fix for issue #27.

Print, but don't fail on deprecation notice

---

.travis.yml

We have decided to no longer support these in our open source stuff.

Remove travis testing of ruby 1.8.7 and puppet 2.7

---

CHANGELOG
lib/puppet-syntax/version.rb

The major version bump is due to the API change in
PuppetSyntax::Manifests#check.
I'm not 100% sure that the major version bump is required, so would appreciate any feedback.

Release version 2.0.0

---

.travis.yml
lib/puppet-syntax.rb
lib/puppet-syntax/manifests.rb
lib/puppet-syntax/tasks/puppet-syntax.rb
lib/puppet-syntax/templates.rb
spec/fixtures/test_module/templates/fail_error.epp
spec/fixtures/test_module/templates/fail_error_also.epp
spec/fixtures/test_module/templates/pass.epp
spec/fixtures/test_module/templates/pass_also.epp
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax/templates_spec.rb
spec/puppet-syntax_spec.rb

This PR has an overarching theme, Puppet 4 time! This PR contains commits that bring this project into working order with Puppet 4. For the most part the project was already there. Manifest validation in Puppet 4 worked just fine, but the unit tests needed to be updated. The only thing missing was EPP template support. That has been added too.

Puppet 4 updates and EPP template support

---

.travis.yml
lib/puppet-syntax/tasks/puppet-syntax.rb
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax/tasks/puppet-syntax_spec.rb

This adds 4.3 to the travis.yml and fixes a minor issue in tests when matching an error message.

Update for puppet 4.3

---

Gemfile
lib/puppet-syntax/templates.rb
spec/puppet-syntax/templates_spec.rb

The last versions of puppet 3 provide already enough infrastructure to validate
epp. If that infrastructure is available, use it.

Update puppet4 check to work on future parser implementations

---

lib/puppet-syntax/manifests.rb

TestHelper offers a public API for (re)initialising Puppet reliably,
which is preferable to using initialize_settings. It also avoids
conflicts when multiple libraries call the same method.

Replace Puppet.initialize_settings with Puppet::Test::TestHelper

---

README.md

Use code escapes to avoid the `**` becoming italics

(maint) Slight markdown tweak

---

.travis.yml

We should test puppet-syntax on more puppet and ruby versions.

Test more puppet and ruby versions

---

lib/puppet-syntax/tasks/puppet-syntax.rb
lib/puppet-syntax/templates.rb
spec/fixtures/test_module/templates/ignore.tpl
spec/puppet-syntax/templates_spec.rb

puppet-syntax is trying to validate all files in any /template/ subdirectory, regardless of whether they're actually ERB files or not.
For example, in one of my projects I have some mako template files (like `files/monitoring/bin/scripts/templates/user_msg.tpl`). Mako templates are close enough to ERB to trigger the validator, but of course they fail to pass it. Those files shouldn't be checked at all, as they do not end in .erb nor are they in the top-level `templates/` directory.

Only try to validate .erb or .epp files

---

README.md
lib/puppet-syntax.rb
lib/puppet-syntax/manifests.rb
lib/puppet-syntax/tasks/puppet-syntax.rb
spec/fixtures/test_module/manifests/test_app.pp
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax/tasks/puppet-syntax_spec.rb
spec/puppet-syntax_spec.rb

Prior to this commit code written for application orchestration could
not be parsed correctly.  This commit adds support for this feature.

Adding Support for `app_management` flag

---

README.md

Noticed the use on the fail_on_deprecation_notices flag was not covered in the README.md, so I added a few words.

Updated documentation to include the fail_on_deprecation_notices flag

---

.travis.yml
CHANGELOG
lib/puppet-syntax/version.rb
puppet-syntax.gemspec

Adds automated gem publishing, gemspec changes for the VP migration and lastly, a 2.3.0 bump and changelog.

Prepare 2.3.0 release

---

.travis.yml
Gemfile
README.md
lib/puppet-syntax.rb
lib/puppet-syntax/manifests.rb
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax_spec.rb

Fixes two failures under Puppet 5.0.0 from master.
master test on Travis CI will fail until the version number is incremented in https://github.com/puppetlabs/puppet/pull/5603.

Test Puppet 5 from master, don't set app_management

---

README.md
lib/puppet-syntax.rb
lib/puppet-syntax/hiera.rb
puppet-syntax.gemspec
spec/fixtures/hiera/hiera_badkey.yaml
spec/puppet-syntax/hiera_spec.rb

Resurrected from #57
* Add regexes for checking hiera key formats
* Enabled by flag 'check_hiera_keys' which is disabled by default as 
it's a breaking change
* Adds spec to catch issues
* Also move multiple entry arrays into separate lines to make cleaner
git history
* Add pry and rb-readline to the development dependancies to make 
development debugging easier

Allow deeper checking of hiera keys

---

lib/puppet-syntax.rb
lib/puppet-syntax/manifests.rb
lib/puppet-syntax/tasks/puppet-syntax.rb
lib/puppet-syntax/templates.rb
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax/templates_spec.rb
spec/puppet-syntax_spec.rb

`Puppet.version.to_f` on Puppet 4.10.0 will evaluate to `4.1`, causing
test and behavioural changes when conditionals check that the version is
equal or greater than versions such as `4.3`.
Version comparisons that are vulnerable to this have been changed to use
Puppet's versioncmp implementation, while most others only check for
for major version boundaries which is safe.
---
Second commit replaces `Puppet::PUPPETVERSION` with the public `Puppet.version` API.

Use versioncmp to check Puppet version for 4.10.x compatibility

---

lib/puppet-syntax/tasks/puppet-syntax.rb

If the tasks have their own namespace, ex:
```
...
namespace :puppet do
require 'puppet-syntax/tasks/puppet-syntax'
end
...
```
the following error is triggered:
```
Don't know how to build task 'syntax' (see --tasks)
/Users/vlad/.rvm/gems/ruby-2.3.4/gems/puppet-syntax-2.4.0/lib/puppet-syntax/tasks/puppet-syntax.rb:36:in `block (2 levels) in initialize'
/Users/vlad/.rvm/gems/ruby-2.3.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/vlad/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/Users/vlad/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test => puppet:test => puppet:syntax => puppet:syntax:check_puppetlabs_spec_helper
(See full trace by running task with --trace)
```
This PR replaces `Rake::Task[:syntax]` with `task(:syntax)`, thus …

Ensure namespace scope is inherited

---

README.md

Howdy!
As part of the work for the Puppet SDK, I'd like to submit some edits to the Puppet::Syntax README.  I've edited and reorganized the README with best docs practices in mind; of please let me know if I've got something wrong or you'd like me to make adjustments.
Pinging @DavidS for visibility (also, he helped review my changes before this PR).

suggested edits on README

---

.travis.yml
Gemfile
appveyor.yml
puppet-syntax.gemspec

Add appveyor.yml config to allow Windows testing.
The config does not exactly reflect the travis config, because:
- appveyor only supports a set list of ruby versions
- appveyor requires matrix combinations to be listed explicitly

Add appveyor config for Windows testing.

---

lib/puppet-syntax/tasks/puppet-syntax.rb

Prior to this fix, when the task will fail with a RunTimeError
when it encounters a failure or warning. This leads to a very ugly
Ruby stacktrace in STDERR. With this fix, the task will print the
warnings to STDOUT, and exit with a 1 exit code to indicate a
failure in the run.
resolves #82

Task does non-zero exit when a syntax error or warning is found.

---

lib/puppet-syntax/tasks/puppet-syntax.rb

b36571a assumed that the `check` method for template and Hiera files
would return a boolean and lines of output, but the API is slightly
different between them and the manifest checks. This restores the
original check for `errors.empty?` instead.

Fix error checking in template and Hiera validation tasks

---

lib/puppet-syntax/hiera.rb
spec/fixtures/hiera/hiera_bad.eyaml
spec/puppet-syntax/hiera_spec.rb

Revisiting the patch set for issue #56 , this is the code which checks the consistency of encoded blobs.  This time including tests, but without a switch to turn it on or off (it seems unnecessary to me).

check consistency of ENC blobs in eyaml data

---

lib/puppet-syntax.rb

Without this patch, only files ending in .yaml will be checked. This
allows files to also end with .yml.
Fixes #98

Allow .yml as an extension for YAML files.

---

lib/puppet-syntax/tasks/puppet-syntax.rb

The syntax check searches for all `.pp` files in the modules, which includes
.pp `files` in the spec tests of the modules like in `spec/type_aliases`. This can lead to errors like:
```
bundle exec rake syntax 
---> syntax:manifests
Attempt to redefine entity 'http://puppet.com/2016.1/runtime/type/XXX'. Originally set at file:///builds/XXX/manifests/network.pp?line=24&pos=1.
```

search manifests in manifests directory

---

lib/puppet-syntax/tasks/puppet-syntax.rb

Reverts voxpupuli/puppet-syntax#100
From slack...
> @Daneel Noooooooooooo oO This broke our usage of puppet-syntax. We're using a mono repo and therefore require the use of `filelist("**/*.pp")`

Revert "search manifests in manifests directory"

---

.travis.yml
lib/puppet-syntax/manifests.rb

Longer term, it'd be better to use a public interface, but for now, code
for the changes to the private `validate_manifest` method made in
https://github.com/puppetlabs/puppet/pull/6909
See https://tickets.puppetlabs.com/browse/PUP-8984

Support puppet 6.5

---

README.md
lib/puppet-syntax.rb
lib/puppet-syntax/tasks/puppet-syntax.rb
spec/puppet-syntax_spec.rb

This can be useful in various situations, like when setting up a task
for checking a specific environment only (where we might be using
e.g. the future parser, or not allowing deprecations, and so on), or
when using this as part of a CI pipeline, where you might want to check
only the changed files for syntax, to save processing time.
As I currently need to do both, I found this would be the cleanest way to do it.

Allow specifying file paths for manifests and templates too

---

lib/puppet-syntax/manifests.rb

enables the `:tasks` switch if the path matches regular expression and the puppet version is >= 6.x.

add support for validating puppet plans (fixes #95, fixes #96)

---

Gemfile
puppet-syntax.gemspec

The gem is required in: https://github.com/bastelfreak/puppet-syntax/blob/55ea82ff7ed597f89a7507f8d6c9774b2bdb563c/lib/puppet-syntax/templates.rb#L2

Add `puppet` gem as runtime dependency

---

lib/puppet-syntax/manifests.rb
spec/fixtures/test_module/manifests/schedule_notice.pp
spec/puppet-syntax/manifests_spec.rb
spec/puppet-syntax/tasks/puppet-syntax_spec.rb

Syntax checking was failing (exit code 1) when puppet raises a the following warning
```
schedule is a metaparam; this value will inherit to all contained resources in the
```
Applied the same approach as `tag`.

Avoid failure on schedule metaparameter warning

---

lib/puppet-syntax/tasks/puppet-syntax.rb
lib/puppet-syntax/templates.rb
spec/puppet-syntax/templates_spec.rb

Previously the `EvaluatingParser` would implicitly call its own
`#assert_and_report()` method, which in turn hands it over to the
`IssueReporter#assert_and_report()` that tries to utilize puppet's
internal logging but in our rake task this is not properly setup and
thus the logged errors get lost.
The result just leaves the validation summary output, e.g.:
```
Language validation logged 2 errors. Giving up (file: templates/configs/jenkins_casc.sh.epp)
```
Which obviously isn't very helpful to the user.
This commit reworks the epp parsing and validation rake task, so that it
instead prints out a nice summary on `$stderr` that contains all
necessary information, e.g.:
```
ERRORS:
templates/configs/jenkins_casc.sh.epp:1:17: Illegal parameter name. The given name 'CASC_JENKINS_CONFIG' does …
```

print actual template errors on $stderr

---

CHANGELOG.md
lib/puppet-syntax/version.rb

[Full Changelog](https://github.com/voxpupuli/puppet-syntax/compare/v3.0.1...v3.1.0)
**Implemented enhancements:**
- print actual template errors on $stderr [\#125](https://github.com/voxpupuli/puppet-syntax/pull/125) ([foxxx0](https://github.com/foxxx0))
**Merged pull requests:**
- Add ruby2.7 testing, replacing multiple obsolete puppet6 versions [\#124](https://github.com/voxpupuli/puppet-syntax/pull/124) ([DavidS](https://github.com/DavidS))

release 3.1.0

---

.github/workflows/test.yml

Without this bundler ends up pulling in 6.28 and concurrent-ruby 1.2, which is an invalid combination.

Pull in Puppet 6.29 in CI

---

lib/puppet-syntax.rb
lib/puppet-syntax/manifests.rb
lib/puppet-syntax/templates.rb

This allows requiring puppet-syntax without loading all of Puppet, which helps speed up other rake commands.

Lazy load required classes

---

lib/puppet-syntax/hiera.rb

This enables support for Hiera YAML files that contain aliases. As an example, with the current version I see this error:
```
❯ bundle exec rake syntax
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
ERROR: Failed to parse data/mac/2c:4d:54:4f:be:c3.yaml: Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`.
```
This is the file it's referring to: https://github.com/halyard/halyard/blob/main/data/mac/2c%3A4d%3A54%3A4f%3Abe%3Ac3.yaml#L43
This PR adds the aliases: true flag, which seems right to me given that Puppet/Hiera allow aliases when parsing YAML.

support aliases in hiera yaml

---

lib/puppet-syntax/templates.rb

when running syntax:templates on its own, not everything required was apparently loaded

fix "NameError: uninitialized constant Puppet::Util" 

---

lib/puppet-syntax/tasks/puppet-syntax.rb

Previously we got the following output from the `syntax` rake task:
```terminal
$ bundle exec rake syntax
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
```
This is a bit misleading because the `syntax:hiera:yaml` task was indeed called, but it doesn't do anything because
`PuppetSyntax.check_hiera_keys` was false. With this commit the output changes:
```terminal
$ bundle exec rake syntax---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
syntax:hiera:yaml was called, but PuppetSyntax.check_hiera_keys is false. hiera syntax won't be checked
```

Raise warning if hiera check is called but disabled

---

.rubocop_todo.yml
lib/puppet-syntax/hiera.rb
spec/fixtures/hiera/hiera_badkey.yaml
spec/puppet-syntax/hiera_spec.rb

This PR fixes a too greedy regular expression for `rake syntax:hiera`.
Description:
Given these keys in a common.yaml:
```yaml
---
firstkey: 'one'
secondkey: 'two'
mymod::mykey: "%{lookup('firstkey')}%{lookup('secondkey')}"
```
This concatenates the keys 'firstkey' ('one') and 'secondkey' ('two') to 'mykey' ('onetwo').
Because of a too greedy regular expression, this leads to a warning, which shouldn't.
Expected result:
```text
---> syntax:hiera:yaml
#
```
Actual result:
```text
---> syntax:hiera:yaml
WARNING: data/common.yaml: Key :mymod::mykey: string after a function call but before `}` in the value
#
```
Explanation:
The regular expression `/%{.+\('.*'\).+}/` matches `%{lookup('firstkey')}%{lookup('secondkey')}`, which fires the Warning.
The regular expression …

fix too greedy regular expression

---

lib/puppet-syntax.rb

The check exists since a long time and I think it makes sense to enable it by default. This is a potential breaking change, so we should probably wait with merging until the next major release.

Enable Hiera syntax check

---

lib/puppet-syntax/hiera.rb
spec/fixtures/hiera/hiera_key_no_value.yaml
spec/puppet-syntax/hiera_spec.rb

This was reported on slack via @ikonia. with such malformed keys, Hiera just reports a string:
```
irb(main):002> require 'yaml'
=> true
irb(main):003> yamlargs = (Psych::VERSION >= '4.0') ? { aliases: true } : {}
=> {aliases: true}
irb(main):004> hiera_file='spec/fixtures/hiera/hiera_key_no_value.yaml'
=> "spec/fixtures/hiera/hiera_key_no_value.yaml"
irb(main):005> YAML.load_file(hiera_file, **yamlargs)
=> "prometheus::initstyle:sysv prometheus::node_exporter::init_style:sysv"
irb(main):006>
```
And puppetserver will fail to compile a catalog:
```
Notice: Catalog compiled by ***
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, /etc/puppetlabs/code/environments/***.yaml: file does not …
```

Detect Hiera files that are not valid hashes
